import * as attendanceService from './services/attendance';
import * as bookService from './services/book';
import * as borrowingService from './services/borrowing';
import * as categoryService from './services/category';
import * as memberService from './services/member';
import * as metaDataService from './services/meta_data';
import * as settingService from './services/setting';
import * as userService from './services/user';

export const getAttendances = (args) => attendanceService.getAttendances(args);
export const addAttendance = (args) => attendanceService.addAttendance(args);
export const getBooks = (args) => bookService.getBooks(args);
export const getBook = (bookId) => bookService.getBook(bookId);
export const addBook = (args) => bookService.addBook(args);
export const updateBook = (args) => bookService.updateBook(args);
export const deleteBook = (args) => bookService.deleteBook(args);
export const getBorrowings = (args) => borrowingService.getBorrowings(args);
export const getBorrowing = (args) => borrowingService.getBorrowing(args);
export const borrowBook = (args) => borrowingService.borrowBook(args);
export const returnBook = (args) => borrowingService.returnBook(args);
export const getCategories = (args) => categoryService.getCategories(args);
export const getCategory = (categoryId) => categoryService.getCategory(categoryId);
export const addCategory = (args) => categoryService.addCategory(args);
export const updateCategory = (args) => categoryService.updateCategory(args);
export const deleteCategory = (args) => categoryService.deleteCategory(args);
export const getRegistrationNumber = () => memberService.getRegistrationNumber();
export const getMembers = (args) => memberService.getMembers(args);
export const getMember = (memberId) => memberService.getMember(memberId);
export const getMemberByRegistrationNumber = (registrationNumber) => memberService.getMemberByRegistrationNumber(registrationNumber);
export const addMember = (args) => memberService.addMember(args);
export const updateMember = (args) => memberService.updateMember(args);
export const deleteMember = (args) => memberService.deleteMember(args);
export const getMetaData = (args) => metaDataService.getMetaData(args);
export const getSetting = () => settingService.getSetting();
export const updateSetting = () => settingService.updateSetting();
export const getUsers = () => userService.getUsers();
export const updatePassword = (args) => userService.updatePassword(args);
export const login = (args) => userService.login(args);
